// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyqdnpqhdodczzaadape.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5cWRucHFoZG9kY3p6YWFkYXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0OTc3NDQsImV4cCI6MjA4NzA3Mzc0NH0.blqoN9IL8jBzmfNymgFu5of6QMHRGEobc2Ok0yc0LUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});